# Travis example for Identifier created by Rafael Garibotti

sudo: false
language: c
compiler:
  - gcc
before_install:
  - sudo apt-get update -y
  - sudo apt-get -y install cppcheck
  - sudo apt-get -y install valgrind
  - sudo apt-get -y install sanitizer
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc
install:
  - "[ $GCC = gcc ] && export GCC=gcc || true"
script:
  - make app
  - make test
  - make cov
  - make cppcheck
  - make valgrind method=selection
  - make valgrind method=insertion
  - make valgrind method=shell
  - make valgrind method=quick
  - make valgrind method=heap
  - make valgrind method=merge
  - make sanitizer method=selection
  - make sanitizer method=insertion
  - make sanitizer method=shell
  - make sanitizer method=quick
  - make sanitizer method=heap
  - make sanitizer method=merge
