# Travis example for Identifier created by Rafael Garibotti

sudo: false
language: c
compiler:
  - gcc
before_install:
  - sudo apt-get update -y
  - sudo apt-get -y install cppcheck
  - sudo apt-get -y install valgrind
  - sudo apt-get -y install sanitizer
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc
install:
  - "[ $GCC = gcc ] && export GCC=gcc || true"
script:
  - make
  - make cov
  - make cppcheck
  - make valgrind
  - make sanitizer
